enum ERROR_CODES{
  SUCCESS = 0,
  SD_INIT_ERROR,
  SD_BLOCK_ERROR,
  SD_WRITE_ERROR,
  SD_READ_ERROR,
  ARG_BUFFER_OVERFLOW,
  ARG_INVALID,
  PAGE_INSUFFICENT_MEMORY,
  PAGE_NO_SUCH_ADDRESS,
  PAGE_PERMISSION_DENIED
};

char error_code;
